
import java.awt.Color;
import javax.swing.JOptionPane;
import db.SessionManager; 
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bihas
 */

public class AdminDashBoardForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardForm
     */
         public AdminDashBoardForm() {
       
        if (!SessionManager.isAdminLoggedIn) {
            JOptionPane.showMessageDialog(null, "Access denied. Please log in first.");
            new RoleSelectionForm().setVisible(true); 
            dispose();
            return; 
       }

        initComponents();
        this.setLocationRelativeTo(null);
     
    
Timer timer = new Timer(1000, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        Date now = new Date();

     
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        lblTime.setText(" " + timeFormat.format(now));

      
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, MMMM dd, yyyy");
        lblDate.setText(" " + dateFormat.format(now));
    }
});
timer.start();

            
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnStudentBack2 = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        Tab3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Tab4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Tab2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Tab1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1499, 854));
        setMinimumSize(new java.awt.Dimension(1499, 854));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1499, 854));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(105, 105, 255));

        jLabel4.setBackground(new java.awt.Color(105, 105, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\menu(2).png")); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("MANAGEMENT SYSTEM");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SCHOOL EVENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 976, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 70));

        jPanel10.setBackground(new java.awt.Color(105, 105, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("STZhongsong", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DASHBOARD");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 134, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("STZhongsong", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADMIN");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 63, 180, -1));

        btnStudentBack2.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentBack2.setText("Logout");
        btnStudentBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBack2ActionPerformed(evt);
            }
        });
        jPanel10.add(btnStudentBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 607, 280, 36));

        lblTime.setFont(new java.awt.Font("STXihei", 1, 40)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, 70));

        lblDate.setFont(new java.awt.Font("STXihei", 1, 26)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 420, 80));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 440, 710));

        Tab3.setBackground(new java.awt.Color(255, 255, 255));
        Tab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 105, 255)));
        Tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab3MouseExited(evt);
            }
        });
        Tab3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\resume.png")); // NOI18N
        Tab3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 21, -1, -1));

        jLabel23.setBackground(new java.awt.Color(105, 105, 255));
        jLabel23.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(105, 105, 255));
        jLabel23.setText("Student Submissions");
        Tab3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 155, 198, -1));

        getContentPane().add(Tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 200, 240, 210));

        Tab4.setBackground(new java.awt.Color(255, 255, 255));
        Tab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 105, 255)));
        Tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab4MouseExited(evt);
            }
        });
        Tab4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\management.png")); // NOI18N
        Tab4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 23, -1, -1));

        jLabel21.setBackground(new java.awt.Color(105, 105, 255));
        jLabel21.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(105, 105, 255));
        jLabel21.setText("User Management");
        Tab4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 157, 180, -1));

        getContentPane().add(Tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 240, 210));

        Tab2.setBackground(new java.awt.Color(255, 255, 255));
        Tab2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 105, 255)));
        Tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab2MouseExited(evt);
            }
        });
        Tab2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\secure-communication.png")); // NOI18N
        Tab2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 18, -1, -1));

        jLabel22.setBackground(new java.awt.Color(105, 105, 255));
        jLabel22.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(105, 105, 255));
        jLabel22.setText("Request Approval");
        Tab2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 158, 180, -1));

        getContentPane().add(Tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 240, 210));

        Tab1.setBackground(new java.awt.Color(255, 255, 255));
        Tab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 105, 255)));
        Tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab1MouseExited(evt);
            }
        });
        Tab1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\events.png")); // NOI18N
        Tab1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel24.setBackground(new java.awt.Color(105, 105, 255));
        jLabel24.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(105, 105, 255));
        jLabel24.setText("Manage Events");
        Tab1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, -1));

        getContentPane().add(Tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 240, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnStudentBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBack2ActionPerformed
        // TODO add your handling code here:
  SessionManager.isAdminLoggedIn = false; 
  JOptionPane.showMessageDialog(this, "Logged out successfully!");
new RoleSelectionForm().setVisible(true); 
dispose(); 

    
    }//GEN-LAST:event_btnStudentBack2ActionPerformed

    private void Tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab2MouseClicked
        // TODO add your handling code here:
        PendingApprovalForm paf = new PendingApprovalForm();
    paf.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Tab2MouseClicked

    private void Tab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab2MouseEntered
        // TODO add your handling code here:
            Tab2.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_Tab2MouseEntered

    private void Tab4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab4MouseEntered
        // TODO add your handling code here:
            Tab4.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_Tab4MouseEntered

    private void Tab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab3MouseEntered
        // TODO add your handling code here:
           Tab3.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_Tab3MouseEntered

    private void Tab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab3MouseExited
        // TODO add your handling code here:
              Tab3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Tab3MouseExited

    private void Tab4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab4MouseExited
        // TODO add your handling code here:
              Tab4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Tab4MouseExited

    private void Tab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab2MouseExited
        // TODO add your handling code here:
             Tab2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Tab2MouseExited

    private void Tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab1MouseClicked
        // TODO add your handling code here:
   ManageEventForm paf = new ManageEventForm();
    paf.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_Tab1MouseClicked

    private void Tab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab1MouseEntered
        // TODO add your handling code here:
         Tab1.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_Tab1MouseEntered

    private void Tab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab1MouseExited
        // TODO add your handling code here:
          Tab1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Tab1MouseExited

    private void Tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab3MouseClicked
        // TODO add your handling code here:
        
    StudentSubmissionForm paf = new StudentSubmissionForm();
    paf.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Tab3MouseClicked

    private void Tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab4MouseClicked
        // TODO add your handling code here:
        UserManagementForm paf = new UserManagementForm();
    paf.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Tab4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tab1;
    private javax.swing.JPanel Tab2;
    private javax.swing.JPanel Tab3;
    private javax.swing.JPanel Tab4;
    private javax.swing.JButton btnStudentBack2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables

}
