/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bihas
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
public class ForgotPasswordForm extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordForm
     */
    public ForgotPasswordForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtStudentID2 = new javax.swing.JTextField();
        txtStudentPassword2 = new javax.swing.JPasswordField();
        btnSubmitRequest = new javax.swing.JButton();
        btnStudentBack2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtStudentPassword1 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtForgotArea = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 530));
        setMinimumSize(new java.awt.Dimension(950, 530));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1343, 754));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 105, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("STXihei", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Forgot Your Password?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, 70));

        jLabel7.setBackground(new java.awt.Color(105, 105, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reason for Password Reset:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student ID :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel11.setBackground(new java.awt.Color(105, 105, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        txtStudentID2.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentID2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 280, 30));

        txtStudentPassword2.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentPassword2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 280, 30));

        btnSubmitRequest.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 280, 30));

        btnStudentBack2.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentBack2.setText("Back");
        btnStudentBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBack2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 280, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("New Password :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtStudentPassword1.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentPassword1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 280, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Confirm New Passwowrd :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        txtForgotArea.setColumns(20);
        txtForgotArea.setRows(5);
        jScrollPane1.setViewportView(txtForgotArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 280, 60));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("STXihei", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Welcome Student !");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 300, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(105, 105, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("MANAGEMENT SYSTEM");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 240, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\undraw_building_websites_i78t.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 880, 690));

        jLabel13.setBackground(new java.awt.Color(105, 105, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 255));
        jLabel13.setText("SCHOOL EVENT");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        // TODO add your handling code here:
  
String studentID = txtStudentID2.getText();
String newPassword = new String(txtStudentPassword1.getPassword());
String confirmPassword = new String(txtStudentPassword2.getPassword());
String reason = txtForgotArea.getText();

if (studentID.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty() || reason.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill out all fields.");
    return;
}

if (!newPassword.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(this, "Passwords do not match.");
    return;
}

try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/event_system", "root", "");


    PreparedStatement checkUser = con.prepareStatement("SELECT * FROM users WHERE student_id = ? AND status = 'approved'");
    checkUser.setString(1, studentID);
    ResultSet userResult = checkUser.executeQuery();

    if (!userResult.next()) {
        JOptionPane.showMessageDialog(this, "Student ID not found or not approved.");
        return;
    }

    String currentPassword = userResult.getString("password");


    if (newPassword.equals(currentPassword)) {
        JOptionPane.showMessageDialog(this, "New password must be different from your current password.");
        return;
    }


    PreparedStatement pendingCheck = con.prepareStatement(
        "SELECT * FROM password_resets WHERE student_id = ? AND status = 'pending'");
    pendingCheck.setString(1, studentID);
    ResultSet pendingResult = pendingCheck.executeQuery();

    if (pendingResult.next()) {
        JOptionPane.showMessageDialog(this, "You already have a pending password reset request.");
        return;
    }


    PreparedStatement ps = con.prepareStatement(
        "INSERT INTO password_resets (student_id, new_password, reason, status) VALUES (?, ?, ?, 'pending')");
    ps.setString(1, studentID);
    ps.setString(2, newPassword);
    ps.setString(3, reason);

    int rowsInserted = ps.executeUpdate();

    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(this, "Password reset request submitted.");
        new StudentLoginForm().setVisible(true);
                this.dispose(); 
    } else {
        JOptionPane.showMessageDialog(this, "Failed to submit request.");
    }

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
}



    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnStudentBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBack2ActionPerformed
        // TODO add your handling code here:
        new StudentLoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudentBack2ActionPerformed

    private void txtStudentPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentPassword2ActionPerformed
        // TODO add your handling code here:
        txtForgotArea.requestFocus();
    }//GEN-LAST:event_txtStudentPassword2ActionPerformed

    private void txtStudentID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentID2ActionPerformed
        // TODO add your handling code here:
        txtStudentPassword1.requestFocus();
    }//GEN-LAST:event_txtStudentID2ActionPerformed

    private void txtStudentPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentPassword1ActionPerformed
        // TODO add your handling code here:
        txtStudentPassword2.requestFocus();
    }//GEN-LAST:event_txtStudentPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentBack2;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtForgotArea;
    private javax.swing.JTextField txtStudentID2;
    private javax.swing.JPasswordField txtStudentPassword1;
    private javax.swing.JPasswordField txtStudentPassword2;
    // End of variables declaration//GEN-END:variables

}
