/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bihas
 */
import db.SessionManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class StudentLoginForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentLoginForm
     */
    public StudentLoginForm() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtStudentPassword = new javax.swing.JPasswordField();
        btnStudentSignup = new javax.swing.JButton();
        btnStudentLogin = new javax.swing.JButton();
        btnStudentBack1 = new javax.swing.JButton();
        btnStudentForgotPassword = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 530));
        setMinimumSize(new java.awt.Dimension(950, 530));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 105, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("STXihei", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login To Your Account");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, 70));

        jLabel5.setBackground(new java.awt.Color(105, 105, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("STXihei", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome Student !");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 300, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student ID :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel9.setBackground(new java.awt.Color(105, 105, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        txtStudentID.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 280, 30));

        txtStudentPassword.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 280, 30));

        btnStudentSignup.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentSignup.setText("Signup");
        btnStudentSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 100, -1));

        btnStudentLogin.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentLogin.setText("Login");
        btnStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 280, 30));

        btnStudentBack1.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentBack1.setText("Back");
        btnStudentBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 280, 30));

        btnStudentForgotPassword.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentForgotPassword.setText("Forgot Password?");
        btnStudentForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentForgotPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(105, 105, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 51));
        jLabel10.setText("MANAGEMENT SYSTEM");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 240, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\undraw_building_websites_i78t.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 880, 690));

        jLabel12.setBackground(new java.awt.Color(105, 105, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(105, 105, 255));
        jLabel12.setText("SCHOOL EVENT");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnStudentSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSignupActionPerformed
        // TODO add your handling code here:
     
    StudentSignUpForm signUp = new StudentSignUpForm();
    signUp.setVisible(true);
    this.dispose();


    }//GEN-LAST:event_btnStudentSignupActionPerformed

    private void btnStudentForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentForgotPasswordActionPerformed
        // TODO add your handling code here:
       
    ForgotPasswordForm forgotPass = new ForgotPasswordForm();
    forgotPass.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_btnStudentForgotPasswordActionPerformed

    private void btnStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentLoginActionPerformed
        // TODO add your handling code here:
  
String studentID = txtStudentID.getText().trim();
String password = new String(txtStudentPassword.getPassword()).trim();

if (studentID.isEmpty() || password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill out all fields.");
    return;
}

if (!studentID.matches("\\d+")) {
    JOptionPane.showMessageDialog(null, "Student ID must contain only numbers.");
    return;
}

try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_system", "root", "")) {

   
    try (PreparedStatement rejectedStmt = con.prepareStatement(
            "SELECT * FROM password_resets WHERE student_id = ? AND status = 'rejected'")) {
        rejectedStmt.setString(1, studentID);
        try (ResultSet rejectedRS = rejectedStmt.executeQuery()) {
            if (rejectedRS.next()) {
                JOptionPane.showMessageDialog(null, "Your password reset request was rejected. You may submit a new one.");
                try (PreparedStatement deleteRejectedStmt = con.prepareStatement(
                        "DELETE FROM password_resets WHERE student_id = ? AND status = 'rejected'")) {
                    deleteRejectedStmt.setString(1, studentID);
                    deleteRejectedStmt.executeUpdate();
                }
            }
        }
    }

    
    try (PreparedStatement approvedStmt = con.prepareStatement(
            "SELECT * FROM password_resets WHERE student_id = ? AND status = 'approved'")) {
        approvedStmt.setString(1, studentID);
        try (ResultSet approvedRS = approvedStmt.executeQuery()) {
            if (approvedRS.next()) {
                JOptionPane.showMessageDialog(null, "Your password reset request was approved. You can now use your new password.");
                try (PreparedStatement deleteApprovedStmt = con.prepareStatement(
                        "DELETE FROM password_resets WHERE student_id = ? AND status = 'approved'")) {
                    deleteApprovedStmt.setString(1, studentID);
                    deleteApprovedStmt.executeUpdate();
                }
            }
        }
    }

    
    try (PreparedStatement stmt = con.prepareStatement("SELECT * FROM users WHERE student_id = ?")) {
        stmt.setString(1, studentID);
        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                String storedPassword = rs.getString("password");
                String status = rs.getString("status");
                boolean firstLoginNotice = rs.getBoolean("first_login_notice");
                boolean isEnabled = rs.getBoolean("is_enabled");

                if (!isEnabled) {
                    JOptionPane.showMessageDialog(null, "Your account has been disabled. Please contact the administrator.");
                    return;
                }

                if (!password.equals(storedPassword)) {
                    JOptionPane.showMessageDialog(null, "Incorrect password.");
                    return;
                }

                if ("approved".equalsIgnoreCase(status)) {
                    if (firstLoginNotice) {
                        JOptionPane.showMessageDialog(null, "Your account has been approved. Welcome!");

                        
                        try (PreparedStatement updateStmt = con.prepareStatement(
                                "UPDATE users SET first_login_notice = FALSE WHERE student_id = ?")) {
                            updateStmt.setString(1, studentID);
                            updateStmt.executeUpdate();
                        }
                    }

                    JOptionPane.showMessageDialog(null, "Login successful!");

                    String studentCourse = rs.getString("course");

                   
                    SessionManager.isStudentLoggedIn = true;
                    SessionManager.loggedInStudentId = studentID;

                  
                    StudentDashBoardForm dashboard = new StudentDashBoardForm();
                    dashboard.setStudentDetails(studentCourse, studentID);
                    dashboard.setVisible(true);
                    this.dispose();

                } else if ("pending".equalsIgnoreCase(status)) {
                    JOptionPane.showMessageDialog(null, "Your account is still pending approval. Please wait.");
                } else if ("rejected".equalsIgnoreCase(status)) {
                    JOptionPane.showMessageDialog(null, "Your account has been rejected and will now be removed.");
                    try (PreparedStatement deleteStmt = con.prepareStatement("DELETE FROM users WHERE student_id = ?")) {
                        deleteStmt.setString(1, studentID);
                        deleteStmt.executeUpdate();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Account not found.");
            }
        }
    }

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
}





    }//GEN-LAST:event_btnStudentLoginActionPerformed

    private void btnStudentBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBack1ActionPerformed
        // TODO add your handling code here:
           new RoleSelectionForm().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnStudentBack1ActionPerformed

    private void txtStudentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentPasswordActionPerformed
        // TODO add your handling code here:
        btnStudentLogin.doClick();
    }//GEN-LAST:event_txtStudentPasswordActionPerformed

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
        txtStudentPassword.requestFocus();
    }//GEN-LAST:event_txtStudentIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentBack1;
    private javax.swing.JButton btnStudentForgotPassword;
    private javax.swing.JButton btnStudentLogin;
    private javax.swing.JButton btnStudentSignup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JPasswordField txtStudentPassword;
    // End of variables declaration//GEN-END:variables
}
