/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bihas
 */
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;




public class StudentSignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentSignUpForm
     */
    public StudentSignUpForm() {
    initComponents();
    loadCoursesFromDatabase(); 
    this.setLocationRelativeTo(null);

    cmbCourse.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyPressed(java.awt.event.KeyEvent e) {
            if (e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                btnStudentRegister.doClick();
            }
        }
    });
}

    
    private void loadCoursesFromDatabase() {
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_system", "root", "");
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT course_name FROM courses ORDER BY course_name ASC")) {

        cmbCourse.removeAllItems();
        cmbCourse.addItem("-- Select Course --");

        while (rs.next()) {
            cmbCourse.addItem(rs.getString("course_name"));
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load courses from database.");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtStudentFullname = new javax.swing.JTextField();
        btnStudentRegister = new javax.swing.JButton();
        btnStudentBack3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtStudentPasswordReset = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtStudentID1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 530));
        setMinimumSize(new java.awt.Dimension(950, 530));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1343, 754));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 105, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("STXihei", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Create Your Account ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, 70));

        jLabel7.setBackground(new java.awt.Color(105, 105, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Full name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel11.setBackground(new java.awt.Color(105, 105, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        txtStudentFullname.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentFullnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 280, 30));

        btnStudentRegister.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentRegister.setText("Register");
        btnStudentRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 280, 30));

        btnStudentBack3.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        btnStudentBack3.setText("Back");
        btnStudentBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudentBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 280, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Course :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        txtStudentPasswordReset.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentPasswordReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentPasswordResetActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentPasswordReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 280, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("STXihei", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Welcome Student !");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 300, 50));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student ID :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtStudentID1.setFont(new java.awt.Font("STXihei", 0, 14)); // NOI18N
        txtStudentID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentID1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 280, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("STXihei", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jPanel1.add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 280, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(105, 105, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("MANAGEMENT SYSTEM");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 240, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bihas\\Downloads\\undraw_building_websites_i78t.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 880, 690));

        jLabel13.setBackground(new java.awt.Color(105, 105, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(105, 105, 255));
        jLabel13.setText("SCHOOL EVENT");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnStudentRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegisterActionPerformed
        // TODO add your handling code here:
String studentID = txtStudentID1.getText().trim();
String fullName = txtStudentFullname.getText().trim();
String password = new String(txtStudentPasswordReset.getPassword());
String course = cmbCourse.getSelectedItem().toString(); 


if (studentID.isEmpty() || fullName.isEmpty() || password.isEmpty() || course.equals("-- Select Course --")) {
    JOptionPane.showMessageDialog(null, "Please fill out all fields and select a valid course.");
    return;
}


if (!studentID.matches("[0-9\\-]+")) {
    JOptionPane.showMessageDialog(null, "Student ID must contain only numbers.");
    return;
}


if (!fullName.matches("[a-zA-Z\\s]+")) {
    JOptionPane.showMessageDialog(null, "Full name must contain only letters and spaces.");
    return;
}

try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/event_system", "root", "");


    String checkQuery = "SELECT * FROM users WHERE student_id = ?";
    PreparedStatement checkStmt = con.prepareStatement(checkQuery);
    checkStmt.setString(1, studentID);
    ResultSet rs = checkStmt.executeQuery();

    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "Student ID already exists. Please use a different ID.");
        return;
    }


    String query = "INSERT INTO users (student_id, full_name, password, course, status) VALUES (?, ?, ?, ?, ?)";
    PreparedStatement stmt = con.prepareStatement(query);
    stmt.setString(1, studentID);
    stmt.setString(2, fullName);
    stmt.setString(3, password);
    stmt.setString(4, course);
    stmt.setString(5, "pending");

    int result = stmt.executeUpdate();

    if (result > 0) {
        JOptionPane.showMessageDialog(null, "Registration successful! Your account is pending approval.");
        txtStudentID1.setText("");
        txtStudentFullname.setText("");
        txtStudentPasswordReset.setText("");
        cmbCourse.setSelectedIndex(0); 
        new StudentLoginForm().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Registration failed. Please try again.");
    }
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
}



    

    }//GEN-LAST:event_btnStudentRegisterActionPerformed

    private void btnStudentBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBack3ActionPerformed
        // TODO add your handling code here:
        new StudentLoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudentBack3ActionPerformed

    private void txtStudentID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentID1ActionPerformed
        // TODO add your handling code here:
        txtStudentFullname.requestFocus();
    }//GEN-LAST:event_txtStudentID1ActionPerformed

    private void txtStudentFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentFullnameActionPerformed
        // TODO add your handling code here:
        txtStudentPasswordReset.requestFocus();
    }//GEN-LAST:event_txtStudentFullnameActionPerformed

    private void txtStudentPasswordResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentPasswordResetActionPerformed
        // TODO add your handling code here:
        cmbCourse.requestFocus();
    }//GEN-LAST:event_txtStudentPasswordResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentBack3;
    private javax.swing.JButton btnStudentRegister;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtStudentFullname;
    private javax.swing.JTextField txtStudentID1;
    private javax.swing.JPasswordField txtStudentPasswordReset;
    // End of variables declaration//GEN-END:variables
}
